services:
  - type: web
    name: task-manager-app
    env: node
    plan: free
    buildCommand: "cd frontend && npm install --include=dev && npm run build && cd ../backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
